More spatial product data, NEON site-level error propogation, NEON forest data query.
EcoForecast/NEFI_microbe pull request #2
Opened 2018-06-28 20:56 UTC by colinaverill

added more worldclim2 variables to worldclim2_grab.r function.
added code to extract global aridity index from spatial product.
wrote script to aggregate NEON site level means for site level forecast.
wrote code to query NEON forest inventory data.
code to aggregate NEON forest data to plot scale still a work in progress.

2018-06-28 23:52 UTC, mdietze requested changes
I appreciate your productivity, but with these really large PR it's pretty had to take anything other than a very superficial look at the submitted code.

2018-06-28 23:52 UTC, mdietze commented on NEFI_functions/arid_extract.r
> +  path <- '/fs/data3/caverill/Global_Aridity/aridity/w001001.adf'
delete this line, it overwrites the input path and is the same as the default.

2018-06-28 23:52 UTC, mdietze commented on NEFI_functions/worldclim2_grab.r
> +  prec    <- raster::raster('/fs/data3/caverill/WorldClim2/wc2.0_bio_30s_12.tif')
would be good to generalize codes like this and have the folder be a variable, then combine it with the file name using `file.path`. This will make the code much more portable

2018-06-28 23:52 UTC, mdietze commented on data_construction/priorITS_tedersoo/formatting_tedersoo_2014_ITS_prior.R
>  source('/home/caverill/NEFI_microbe/NEFI_functions/fg_assign.r')
more paths that can be generalized

2018-06-28 23:52 UTC, mdietze commented on testing_development/global aridity index extract.r
> +arid_extract <- function(latitude, longitude, path = '/fs/data3/caverill/Global_Aridity/aridity/w001001.adf'){
is the same function defined in another folder?

2018-06-28 23:52 UTC, mdietze commented on testing_development/implement_missing_data_ddirch/ddirch_missing.data_site.level.only_function_parm.cov.r
> +  source('/home/caverill/NEFI_microbe/NEFI_functions/precision_matrix_match.r')
Seems pretty unsafe to have `source` within a function, particularly with hard-coded paths

2018-06-29 14:07 UTC, colinaverill commented
Apologies on the large pull. One of my goals this summer is actually stay on top of my githubbing, so pulls from now on should be smaller. In the future I will break these up into smaller commits and pull requests, but this may result in multiple pull requests a day. Also- all the code on testing_development is pretty hacky, and not intended as production code, just scripts I wrote to convince myself things are working and I'm not ready to delete yet. These are the things I asked if it made sense to keep in a separate repo outside of the main branch. Hence there a development versions of functions that are now in the actual functions folder, and other weird stuff.

2018-06-29 14:17 UTC, colinaverill commented on testing_development/implement_missing_data_ddirch/ddirch_missing.data_site.level.only_function_parm.cov.r
> +  source('/home/caverill/NEFI_microbe/NEFI_functions/precision_matrix_match.r')
Gotcha. Is there a better way to have a function depend on other functions?

2018-06-29 14:18 UTC, colinaverill commented on NEFI_functions/arid_extract.r
> +  path <- '/fs/data3/caverill/Global_Aridity/aridity/w001001.adf'
done, also changed folder to a variable.

2018-06-29 14:18 UTC, colinaverill commented on NEFI_functions/worldclim2_grab.r
> +  prec    <- raster::raster('/fs/data3/caverill/WorldClim2/wc2.0_bio_30s_12.tif')
generalized folder to be a variable in the function.

2018-06-29 14:18 UTC, colinaverill commented on data_construction/priorITS_tedersoo/formatting_tedersoo_2014_ITS_prior.R
>  source('/home/caverill/NEFI_microbe/NEFI_functions/fg_assign.r')
done.

2018-06-29 14:18 UTC, colinaverill commented on testing_development/global aridity index extract.r
> +arid_extract <- function(latitude, longitude, path = '/fs/data3/caverill/Global_Aridity/aridity/w001001.adf'){
yup. This is a relic from when i was developing the function. Most things in the testing_development folder will eventually be deleted.

2018-06-29 14:35 UTC, mdietze commented on testing_development/implement_missing_data_ddirch/ddirch_missing.data_site.level.only_function_parm.cov.r
> +  source('/home/caverill/NEFI_microbe/NEFI_functions/precision_matrix_match.r')
Well, best would be to put them all in a package, but in lieu of that I'd put these source calls in the same file but outside the function itself so they are called once when this function is loaded, not re-called every time the function is executed

2018-06-29 14:36 UTC, mdietze commented on testing_development/global aridity index extract.r
> +arid_extract <- function(latitude, longitude, path = '/fs/data3/caverill/Global_Aridity/aridity/w001001.adf'){
If you just wholesale move a file from one folder to another, use `git mv` as that will tell git that you moved it to a new place but it's the same file and stays associated with the same development history

2018-06-29 21:31 UTC, colinaverill commented
Apologies, I added more commits to this pull request (had planned to submit a new PR but this one has not been accepted yet).

2018-06-29 21:32 UTC, colinaverill commented on testing_development/global aridity index extract.r
> +arid_extract <- function(latitude, longitude, path = '/fs/data3/caverill/Global_Aridity/aridity/w001001.adf'){
Will do. In this case I actually just copy paste this function into a new file and left the old one... which I will delete eventually.

2018-06-29 21:33 UTC, colinaverill commented on testing_development/implement_missing_data_ddirch/ddirch_missing.data_site.level.only_function_parm.cov.r
> +  source('/home/caverill/NEFI_microbe/NEFI_functions/precision_matrix_match.r')
okay. I am going to leave this one as is, as this is a testing_development script, nothing important depends on it, it will be deleted eventually.

2018-06-29 21:36 UTC, mdietze approved these changes

2018-06-29 21:36 UTC, mdietze commented on NEFI_functions/worldclim2_grab.r
> +  prec    <- raster::raster(paste0(worldclim2_folder,'wc2.0_bio_30s_12.tif'))
For future reference, file.path is safer here than paste0, which can f* up depending on slashes and what not.

2018-06-29 21:37 UTC, mdietze commented
> Apologies, I added more commits to this pull request (had planned to submit a new PR but this one has not been accepted yet).

@colinaverill that's what branches are for

2018-06-29 21:37 UTC, merged

2018-06-29 21:39 UTC, colinaverill commented
riiiiight. Next week branching is on the top of my list. This is better than just submitting a pile of commits?

2018-06-29 21:42 UTC, mdietze commented
Well, maybe not 'better', but it does allow you to keep one pile of commits distinct from another pile of commits. So, for example, you could submit a PR for one feature while continuing to work on another feature in a different branch. This helps solve the 'testing' code folder you had -- a set of test code could live in a separate branch, and only get pulled into the mainline when it's working.